name: Blue-Green CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      target:
        description: "Selecciona BLUE o GREEN"
        required: true
        default: "GREEN"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USER }}/blue-green-app:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USER }}/blue-green-app:latest

    # ========================================
    # DETERMINAR TARGET AUTOMÃTICO
    # ========================================

    - name: Determine target from push (auto swap)
      if: github.event_name == 'push'
      run: |
        CURRENT=$(cat app/current_version.txt)
        echo "CURRENT VERSION = $CURRENT"

        if [ "$CURRENT" = "BLUE" ]; then
          echo "TARGET=GREEN" >> $GITHUB_ENV
        else
          echo "TARGET=BLUE" >> $GITHUB_ENV
        fi

    - name: Determine target from dispatch (manual)
      if: github.event_name == 'workflow_dispatch'
      run: echo "TARGET=${{ github.event.inputs.target }}" >> $GITHUB_ENV

    - name: Show selected TARGET
      run: echo "Deploying to $TARGET"

    # ========================================
    # DEPLOY BLUE
    # ========================================

    - name: Deploy BLUE
      if: env.TARGET == 'BLUE'
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /var/www/blue-green-deploy
          git pull origin main
          chmod +x scripts/*.sh
          bash scripts/deploy_blue.sh

          docker exec app-blue sh -c "echo BLUE > /usr/share/nginx/html/current_version.txt"

          bash scripts/switch_to_blue.sh


    # ========================================
    # DEPLOY GREEN
    # ========================================

    - name: Deploy GREEN
      if: env.TARGET == 'GREEN'
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /var/www/blue-green-deploy
          git pull origin main
          chmod +x scripts/*.sh
          bash scripts/deploy_green.sh

          docker exec app-green sh -c "echo GREEN > /usr/share/nginx/html/current_version.txt"

          bash scripts/switch_to_green.sh
