name: Blue-Green CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      target:
        description: "Selecciona el entorno a desplegar (BLUE o GREEN)"
        required: true
        default: "GREEN"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USER }}/blue-green-app:latest .

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USER }}/blue-green-app:latest

    # ============================
    # DEPLOY BLUE
    # ============================
    - name: Deploy BLUE on server and switch traffic
      if: ${{ github.event.inputs.target == 'BLUE' }}
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /var/www/blue-green-deploy
          git pull origin main
          chmod +x scripts/*.sh
          bash scripts/deploy_blue.sh
          bash scripts/switch_to_blue.sh

    # ============================
    # DEPLOY GREEN
    # ============================
    - name: Deploy GREEN on server and switch traffic
      if: ${{ github.event.inputs.target == 'GREEN' }}
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /var/www/blue-green-deploy
          git pull origin main
          chmod +x scripts/*.sh
          bash scripts/deploy_green.sh
          bash scripts/switch_to_green.sh
