name: Blue-Green CI/CD

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Selecciona el entorno a desplegar (BLUE o GREEN)"
        required: true
        default: "GREEN"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Login Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Build Image
      run: docker build -t ${{ secrets.DOCKER_USER }}/blue-green-app:latest .

    - name: Push Image
      run: docker push ${{ secrets.DOCKER_USER }}/blue-green-app:latest

    # OBTENER TARGET DESDE INPUT
    - name: Set environment target
      run: echo "TARGET=${{ github.event.inputs.target }}" >> $GITHUB_ENV

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /var/www/blue-green-deploy
          git pull origin main
          chmod +x scripts/*.sh

          if [ "$TARGET" = "BLUE" ]; then
            bash scripts/deploy_blue.sh
            bash scripts/switch_to_blue.sh
          else
            bash scripts/deploy_green.sh
            bash scripts/switch_to_green.sh
          fi
